apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/mainflux-base-net: "true"
    io.kompose.service: auth
  name: auth
spec:
  containers:
  - env:
    - name: MF_AUTH_DB
      value: auth
    - name: MF_AUTH_DB_HOST
      value: auth-db
    - name: MF_AUTH_DB_PASS
      value: mainflux
    - name: MF_AUTH_DB_PORT
      value: "5432"
    - name: MF_AUTH_DB_USER
      value: mainflux
    - name: MF_AUTH_GRPC_PORT
      value: "8181"
    - name: MF_AUTH_HTTP_PORT
      value: "8189"
    - name: MF_AUTH_LOG_LEVEL
      value: debug
    - name: MF_AUTH_SECRET
      value: secret
    - name: MF_JAEGER_URL
      value: jaeger:6831
    image: mainflux/auth:latest
    name: mainflux-auth
    ports:
    - containerPort: 8189
    - containerPort: 8181
    resources: {}
  restartPolicy: OnFailure
status: {}
