apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/mainflux-base-net: "true"
    io.kompose.service: http-adapter
  name: http-adapter
spec:
  containers:
  - env:
    - name: MF_HTTP_ADAPTER_LOG_LEVEL
      value: debug
    - name: MF_HTTP_ADAPTER_PORT
      value: "8185"
    - name: MF_JAEGER_URL
      value: jaeger:6831
    - name: MF_NATS_URL
      value: nats://nats:4222
    - name: MF_THINGS_AUTH_GRPC_TIMEOUT
      value: 1s
    - name: MF_THINGS_AUTH_GRPC_URL
      value: things:8183
    image: mainflux/http:latest
    name: mainflux-http
    ports:
    - containerPort: 8185
    resources: {}
  restartPolicy: OnFailure
status: {}
