apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  # clusterIP: None
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30000
    name: postgres
  selector:
    app: postgres