apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: things
  name: things
spec:
  ports:
  - name: "8182"
    port: 8182
    targetPort: 8182
  - name: "8989"
    port: 8989
    targetPort: 8989
  - name: "8183"
    port: 8183
    targetPort: 8183
  selector:
    io.kompose.service: things
status:
  loadBalancer: {}
