apiVersion: v1
kind: Service
metadata:
  name: mqtt-tttm-service
  labels:
    app: mqtt-tttm
spec:
  type: NodePort
  ports:
    - port: 1886
      name: mqttPort
    - port: 8080
      name: htttpPort
  selector:
    app: mqtt-tttm
