apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /postgres1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /postgres2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres3
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /postgres3