replicaCount: 2

service:
    type: NodePort 
    mqtt:
        enabled: true
        port: 1883
        nodePort: 30030

additionalEnv:
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"

persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: local-storage
    accessModes:
        - ReadWriteOnce