apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-ext
  namespace: default
spec:
  type: ExternalName
  externalName: my.nginx.com
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
  