apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  ports:
    - name: "8189"
      port: 8189
      targetPort: 8189
    - name: "8181"
      port: 8181
      targetPort: 8181
  selector:
    io.kompose.service: auth
status:
  loadBalancer: {}
