apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.network/mainflux-base-net: "true"
    io.kompose.service: influxdb-writer
  name: influxdb-writer
spec:
  containers:
    - env:
        - name: MF_INFLUX_WRITER_BATCH_SIZE
          value: "5000"
        - name: MF_INFLUX_WRITER_BATCH_TIMEOUT
          value: "5"
        - name: MF_INFLUX_WRITER_DB
          value: mainflux
        - name: MF_INFLUX_WRITER_DB_HOST
          value: mainflux-influxdb
        - name: MF_INFLUX_WRITER_DB_PASS
          value: mainflux
        - name: MF_INFLUX_WRITER_DB_PORT
          value: "8086"
        - name: MF_INFLUX_WRITER_DB_USER
          value: mainflux
        - name: MF_INFLUX_WRITER_LOG_LEVEL
          value: debug
        - name: MF_INFLUX_WRITER_PORT
          value: "8900"
        - name: MF_NATS_URL
          value: nats://nats:4222
      image: mainflux/influxdb-writer:latest
      name: mainflux-influxdb-writer
      ports:
        - containerPort: 8900
      resources: {}
      volumeMounts:
        - mountPath: /config/subjects.toml
          name: influxdb-writer-claim0
  restartPolicy: OnFailure
  volumes:
    - name: influxdb-writer-claim0
      persistentVolumeClaim:
        claimName: influxdb-writer-claim0
status: {}
