apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.network/mainflux-base-net: "true"
    io.kompose.service: influxdb
  name: influxdb
spec:
  containers:
    - env:
        - name: INFLUXDB_ADMIN_PASSWORD
          value: mainflux
        - name: INFLUXDB_ADMIN_USER
          value: mainflux
        - name: INFLUXDB_DB
          value: mainflux
      image: influxdb:1.8.3
      name: mainflux-influxdb
      ports:
        - containerPort: 8086
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/influxdb
          name: mainflux-influxdb-volume
  restartPolicy: OnFailure
  volumes:
    - name: mainflux-influxdb-volume
      persistentVolumeClaim:
        claimName: mainflux-influxdb-volume
status: {}
