apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.network/mainflux-base-net: "true"
    io.kompose.service: opcua-adapter
  name: opcua-adapter
spec:
  containers:
    - env:
        - name: MF_NATS_URL
          value: nats://nats:4222
        - name: MF_OPCUA_ADAPTER_CERT_FILE
        - name: MF_OPCUA_ADAPTER_EVENT_CONSUMER
          value: opcua
        - name: MF_OPCUA_ADAPTER_HTTP_PORT
          value: "8188"
        - name: MF_OPCUA_ADAPTER_KEY_FILE
        - name: MF_OPCUA_ADAPTER_LOG_LEVEL
          value: debug
        - name: MF_OPCUA_ADAPTER_MODE
        - name: MF_OPCUA_ADAPTER_POLICY
        - name: MF_OPCUA_ADAPTER_ROUTE_MAP_DB
          value: "0"
        - name: MF_OPCUA_ADAPTER_ROUTE_MAP_PASS
        - name: MF_OPCUA_ADAPTER_ROUTE_MAP_URL
          value: opcua-redis:6379
        - name: MF_THINGS_ES_DB
          value: "0"
        - name: MF_THINGS_ES_PASS
        - name: MF_THINGS_ES_URL
          value: es-redis:6379
      image: mainflux/opcua:latest
      name: mainflux-opcua
      ports:
        - containerPort: 8188
      resources: {}
      volumeMounts:
        - mountPath: /store
          name: mainflux-opcua-adapter-volume
  restartPolicy: OnFailure
  volumes:
    - name: mainflux-opcua-adapter-volume
      persistentVolumeClaim:
        claimName: mainflux-opcua-adapter-volume
status: {}
