apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.network/mainflux-base-net: "true"
    io.kompose.service: twins-db
  name: twins-db
spec:
  containers:
    - args:
        - mongod
        - --port
        - "27018"
      env:
        - name: MONGO_INITDB_DATABASE
          value: mainflux-twins
      image: mongo:bionic
      name: mainflux-twins-db
      ports:
        - containerPort: 27018
      resources: {}
      volumeMounts:
        - mountPath: /data/db
          name: mainflux-twins-db-volume
        - mountPath: /data/configdb
          name: mainflux-twins-db-configdb-volume
  restartPolicy: OnFailure
  volumes:
    - name: mainflux-twins-db-volume
      persistentVolumeClaim:
        claimName: mainflux-twins-db-volume
    - name: mainflux-twins-db-configdb-volume
      persistentVolumeClaim:
        claimName: mainflux-twins-db-configdb-volume
status: {}
